# Site settings
title: Makoto Museum
email: yushi.nakai@gmail.com
description: >
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://makoto.isasaka.net"
image_base: "https://copy.com/Gd1RKoBWwFFIwBVv/museum/makoto/"
image_suffix: "?download=1"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

exclude:
 - /vendor
